### ISSUE TITLE
No module named scalene

### ISSUE THREAD

**Issue by sumanthratna** [plasma-umass/homebrew-scalene#1]
I have python@3.8 and python@3.9 installed with Homebrew. I ran `brew install --HEAD emeryberger/scalene/libscalene` and then tried running `scalene --help` but instead I get exit code 1 with this output: `/usr/local/opt/python@3.8/bin/python3.8: No module named scalene`

**Comment by emeryberger** [comment]
The homebrew tap has been unnecessary for some time (and has been ignored, sorry for the long delay in response!). Please use `pip` instead.
